"""Add added_date column to suspicious domain

Revision ID: 9c9f8e2dde3a
Revises: 
Create Date: 2025-09-29 16:08:46.372331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9f8e2dde3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suspicious_domain', sa.Column('added_date', sa.DateTime(), nullable=False, server_default=sa.text("NOW()")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suspicious_domain', 'added_date')
    # ### end Alembic commands ###
